name: publish
on: release
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        if: github.event.action == 'published'
        with:
          node-version: 12
      - run: npm ci
        if: github.event.action == 'published'
      - run: |
          GH_TOKEN=${PRE_GH_TOKEN:3:43} npm run release
        if: github.event.action == 'published'
        env:
          PRE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_REPO_SLUG: corporateclash/corporate-clash-launcher
          CI_BUILD_TAG: ${{ github.event.release.tag_name }}
