name: publish
on:
  release:
      types: [published]
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest]
    env:
      EP_PRE_RELEASE: true
      TRAVIS_REPO_SLUG: corporateclash/corporate-clash-launcher
      CI_BUILD_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Temporarily fix electron-builder WIN
        run: |
          sed -i 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
        shell: bash
        if: matrix.os == 'windows-latest'
      - name: Temporarily fix electron-builder MAC
        run: |
          sed -i '' 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
        shell: bash
        if: matrix.os == 'macOS-latest'
      - run: npm run release
        shell: bash
        if: matrix.os == 'macOS-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          CSC_LINK: ${{ secrets.CSC_MAC_BASE64 }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_MAC_PASSWORD }}
      - run: npm run release
        shell: bash
        if: matrix.os == 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
