name: publish
on:
  release:
      types: [published]
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Temporarily fix electron-builder
        run: |
          sed -i 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
        shell: bash
      - run: |
          npm run release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_PRE_RELEASE: true
          TRAVIS_REPO_SLUG: corporateclash/corporate-clash-launcher
          CI_BUILD_TAG: ${{ github.event.release.tag_name }}
