name: publish
on: release
jobs:
  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        if: github.event.action == 'published'
        with:
          node-version: 12
      - run: npm ci
        if: github.event.action == 'published'
      - run: npm run release
        if: github.event.action == 'published'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_REPO_SLUG: corporateclash/corporate-clash-launcher
          CI_BUILD_TAG: ${{ github.event.release.tag_name }}
